### ISSUE TITLE
Replace loading screen with custom splash screen

### ISSUE THREAD

**Issue by ashwinkey04** [raag-music/raag#14]
The app currently has a circular progress bar which will be shown while fetching the local mp3 files. Need to replace that with a simple splash screen which would go off after the music is fetched

**Comment by yuvi0069** [comment]
HI YUVRAJ SINGH YADAV FROM DSCE BENGALURU. I REPLACED THE CIRCULAR PROGRESS WITH A IMAGE AND AND A SPINKIT. THE CODE IS AS FOLLOWS IN YOUR My_Music_List.dart.
the code as follows-
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_audio_query/flutter_audio_query.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:raag/provider/SongWidget.dart';

class MyMusicList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: FutureBuilder(
        future:
            FlutterAudioQuery().getSongs(sortType: SongSortType.DISPLAY_NAME),
        builder: (context, snapshot) {
          List<SongInfo> songInfo = snapshot.data;
          if (snapshot.hasData) {
            return SongWidget(songList: songInfo);
          }
          return Container(
            padding: EdgeInsets.all(20),
            width: 800,
            color: Colors.black,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Image.asset(
                  'assets/images/pl2.jpg',
                  height: 300,
                ),
                SizedBox(
                  height: 30,
                ),
                SpinKitRipple(color: Colors.red),
              ],
            ),
          );
        },
      ),
    );
  }
}
the pic is as follow
![20201206_153631 1](https://user-images.githubusercontent.com/73466487/101277310-901a3680-37d9-11eb-8bba-ff6d6f1cb1ef.jpg)

**Comment by yuvi0069** [comment]
actually i am working on this issue and solved it with Hero Widget
