### ISSUE TITLE
Implement icon animation

### ISSUE THREAD

**Issue by robustTechie** [raag-music/raag#16]
Add animation in dark mode icon which will animate while switching between light-dark mode.

**Comment by xcyberpunkx0** [comment]
can i work on this issue?

**Comment by robustTechie** [comment]
Hey, @xcyberpunkx0 go ahead, if you have any doubt feel free to ask :)

**Comment by xcyberpunkx0** [comment]
Is this okay?
![AnimatedIcon](https://user-images.githubusercontent.com/53346087/101523454-a1686c00-39ae-11eb-8014-e197ef62ba43.gif)

**Comment by robustTechie** [comment]
Yes
