### ISSUE TITLE
Youtube download not working 

### ISSUE THREAD

**Issue by Thomi7** [raag-music/raag#45]
Installed via F-Droid, version 1.0.0, Android 10 Havoc OS

Is the youtube download functionality working for you?
When I try to download [https://youtu.be/ISliPhV3v2M](https://youtu.be/ISliPhV3v2M) it says Resolving URL forever. Once I got it to the point where the thumbnail and title are shown. But then it got stuck on fetching.

**Comment by ashwinkey04** [comment]
> Installed via F-Droid, version 1.0.0, Android 10 Havoc OS
> 
> Is the youtube download functionality working for you?
> When I try to download https://youtu.be/ISliPhV3v2M it says Resolving URL forever. Once I got it to the point where the thumbnail and title are shown. But then it got stuck on fetching.

We did recieve this feedback from quite a few users. It's a `FilesystemException` but it is occurring in only a few devices. We're working on fixing this

**Comment by Thomi7** [comment]
Ok. Tell me when you need logs or debugging from my side.

**Comment by oilbodod** [comment]
sale problem here.
Zenfone 7 pro, Android 11.

**Comment by doc75** [comment]
Same issue on Galaxy S7 installed with [/e/OS](https://e.foundation/)
@ashwinkey04 any idea on when 1.0.1 will be updated on F-Droid ?

**Comment by ashwinkey04** [comment]
> Same issue on Galaxy S7 installed with [/e/OS](https://e.foundation/)
> @ashwinkey04 any idea on when 1.0.1 will be updated on F-Droid ?

We've submitted two more revisions at F-Droid. Unfortunately none were deployed in their end. We will follow up on this issue. Meanwhile you can download the apk from GitHub's releases page
