### ISSUE TITLE
Downloaded songs not showing up

### ISSUE THREAD

**Issue by lanscapesystems** [raag-music/raag#49]
I installed the latest version from f-droid onto my oneplus 7t running aosip. After downloading a song it shows up in files but ragg does not show it. I reinstalled multiple times and tried moving the song to the music folder.

Any help is appriciated
Andy

**Comment by Glitchy-Tozier** [comment]
Jup, I had (and still have) the same problem. Also tried reinstalling and deleting the app's cache, but nothing helped.

**Comment by ashwinkey04** [comment]
When download location is set to `Android/Data/in.amfoss.raag`, due to issues with scoped storage while saving files, I wasn't yet able to query songs inside that directory. You might have to use the File manager to access those songs until someone/I find a fix for that

**Comment by Glitchy-Tozier** [comment]
@ashwinkey04 Can you point me to the file where you save the songs?

**Comment by ashwinkey04** [comment]
> @ashwinkey04 Can you point me to the file where you save the songs?

You can check the download location on the settings page inside the app.
