### ISSUE TITLE
YT download failing

### ISSUE THREAD

**Issue by hororh** [raag-music/raag#50]
Attempt to download https://youtu.be/AU56pqcKYeY results in:
 [Unknown error](https://www.dropbox.com/s/10pkv6bzi2l16ed/screenshot_20210726-041144.png?dl=1)

**Comment by gitsnead** [comment]
I am also experiencing a download error.
https://m.youtube.com/watch?v=v4LynYmA1IQ
Let me know what debug info would be helpful, and I'll try to provide it.

**Comment by switchcomb** [comment]
Just tried downloading this video using the following two URL strings and got the same error message:

https://youtu.be/DhkgohG9lTM
https://www.youtube.com/watch?v=DhkgohG9lTM

![Screenshot_20210830-170434](https://user-images.githubusercontent.com/26367285/131406107-f6039978-73dc-4fb7-b268-0c25f3198cb3.png)

**Comment by ashwinkey04** [comment]
Thanks for the report. We are working on solving this.
