### ISSUE TITLE
Add changelog to releases

### ISSUE THREAD

**Issue by Glitchy-Tozier** [raag-music/raag#53]
Basically, add a text-file to your metadata.

**Comment by Glitchy-Tozier** [comment]
@ashwinkey04 Thank you for tackling this issue!
Just a small warning: I'm not sure it'll work as intended. As far as I know the changelogs need to be named according to the **build-number**, instead of with the **version-number**. You can find a working example in the metadata of my app: https://github.com/Glitchy-Tozier/githo/tree/main/fastlane/metadata/android/en-US/changelogs

**Comment by ashwinkey04** [comment]
> @ashwinkey04 Thank you for tackling this issue!
> Just a small warning: I'm not sure it'll work as intended. As far as I know the changelogs need to be named according to the **build-number**, instead of with the **version-number**. You can find a working example in the metadata of my app: https://github.com/Glitchy-Tozier/githo/tree/main/fastlane/metadata/android/en-US/changelogs

Ohh, thanks a lot for the clarification. I'll do the necessary changes.
