### ISSUE TITLE
Album art not displayed

### ISSUE THREAD

**Issue by ashwinkey04** [raag-music/raag#7]
**Summary**
Flutter audio query package has a function to fetch the album art of songs. We did implement that, but for reasons unknown it doesn't work. 

**Expected**
Display the album art for songs in list view in place of the default image

**Comment by xcyberpunkx0** [comment]
anyone working on this?

**Comment by robustTechie** [comment]
Hey @xcyberpunkx0 if you want to work on this you can go ahead :)

**Comment by ashwinkey04** [comment]
Fixed
