### ISSUE TITLE
Exclude Whatsapp audio

### ISSUE THREAD

**Issue by ashwinkey04** [raag-music/raag#9]
WhatsApp audio won't count as music but it still is displayed in the app. Avoid listing whatsapp audio files. A simple fix would be to exclude a file if the file path contains the string `'WhatsApp/Media/WhatsApp Audio'`

**Comment by Puja7629** [comment]
May I take this task? KIndly assign this task to me.

**Comment by ashwinkey04** [comment]
Fixed
